### ISSUE TITLE
REST Endpoint Authentication Recover User password

### ISSUE THREAD

**Issue by bmvr** [HelpingHandPT/COVID19-be#29]
Create the workflow to reset user password with a new one.

**Comment by tiago-peres** [comment]
Hint1: https://youtu.be/qjlZWBbX7-o
Hint2: https://simpleisbetterthancomplex.com/tutorial/2016/09/19/how-to-create-password-reset-view.html
Hint3: https://stackoverflow.com/questions/53945056/django-rest-auth-password-reset
